trigger:
  - main
pr:
  - none



pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      import json, os
      with open("package.json", "r+") as jsonFile:
          data = json.load(jsonFile)
          version = data["version"]
          print (version)
          os.system("echo the version is $version")
